truncate table account;
truncate table account_relation;
truncate table account_relation_archive;
truncate table account_tag;
truncate table account_archive;
truncate table error_log;
truncate table media;
truncate table media_archive;
truncate table media_part;
truncate table media_part_tag;
truncate table media_tag;
truncate table post;
truncate table post_archive;
truncate table post_engagement;
truncate table post_engagement_archive;
truncate table post_engagement_tag;
truncate table post_tag;
truncate table tag;
truncate table tag_hierarchy;
truncate table tag_type;
-- Reset AUTO_INCREMENT for all truncated tables
alter table account auto_increment = 1;
alter table account_relation auto_increment = 1;
alter table account_relation_archive auto_increment = 1;
alter table account_tag auto_increment = 1;
alter table account_archive auto_increment = 1;
alter table error_log auto_increment = 1;
alter table media auto_increment = 1;
alter table media_archive auto_increment = 1;
alter table media_part auto_increment = 1;
alter table media_part_tag auto_increment = 1;
alter table media_tag auto_increment = 1;
alter table post auto_increment = 1;
alter table post_archive auto_increment = 1;
alter table post_engagement auto_increment = 1;
alter table post_engagement_archive auto_increment = 1;
alter table post_engagement_tag auto_increment = 1;
alter table post_tag auto_increment = 1;
alter table tag auto_increment = 1;
alter table tag_hierarchy auto_increment = 1;
alter table tag_type auto_increment = 1;

UPDATE archive_session SET extraction_error = NULL, extracted_entities=NULL WHERE TRUE;
UPDATE archive_session SET parsed_content=NULL WHERE TRUE;