truncate table account;
truncate table account_relation;
truncate table account_relation_archive;
truncate table account_tag;
truncate table account_archive;
truncate table comment;
truncate table comment_archive;
truncate table error_log;
truncate table media;
truncate table media_archive;
truncate table media_part;
truncate table media_part_tag;
truncate table media_tag;
truncate table post;
truncate table post_archive;
truncate table post_like;
truncate table post_like_archive;
truncate table post_tag;
truncate table tag;
truncate table tag_hierarchy;
truncate table tag_type;
truncate table tagged_account;
truncate table tagged_account_archive;
-- Reset AUTO_INCREMENT for all truncated tables
alter table account auto_increment = 1;
alter table account_relation auto_increment = 1;
alter table account_relation_archive auto_increment = 1;
alter table account_tag auto_increment = 1;
alter table account_archive auto_increment = 1;
alter table comment auto_increment = 1;
alter table comment_archive auto_increment = 1;
alter table error_log auto_increment = 1;
alter table media auto_increment = 1;
alter table media_archive auto_increment = 1;
alter table media_part auto_increment = 1;
alter table media_part_tag auto_increment = 1;
alter table media_tag auto_increment = 1;
alter table post auto_increment = 1;
alter table post_archive auto_increment = 1;
alter table post_like auto_increment = 1;
alter table post_like_archive auto_increment = 1;
alter table post_tag auto_increment = 1;
alter table tag auto_increment = 1;
alter table tag_hierarchy auto_increment = 1;
alter table tag_type auto_increment = 1;
alter table tagged_account auto_increment = 1;
alter table tagged_account_archive auto_increment = 1;

UPDATE archive_session SET extraction_error = NULL, structures = NULL, extract_algorithm_version = NULL WHERE TRUE;
UPDATE archive_session SET incorporation_status = 'pending' WHERE TRUE;